/* Generated By:JavaCC: Do not edit this line. UnrealScriptParserConstants.java */
package org.unrealscriptsupport.jccparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UnrealScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int ABSTRACT = 8;
  /** RegularExpression Id. */
  int ARRAY = 9;
  /** RegularExpression Id. */
  int AUTO = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int BREAK = 12;
  /** RegularExpression Id. */
  int BYTE = 13;
  /** RegularExpression Id. */
  int CACHEEXEMPT = 14;
  /** RegularExpression Id. */
  int CASE = 15;
  /** RegularExpression Id. */
  int CLASS = 16;
  /** RegularExpression Id. */
  int CLOCKWISEFROM = 17;
  /** RegularExpression Id. */
  int COERCE = 18;
  /** RegularExpression Id. */
  int COLLAPSECATEGORIES = 19;
  /** RegularExpression Id. */
  int CONFIG = 20;
  /** RegularExpression Id. */
  int CONST = 21;
  /** RegularExpression Id. */
  int CONTINUE = 22;
  /** RegularExpression Id. */
  int CROSS = 23;
  /** RegularExpression Id. */
  int _DEFAULT = 24;
  /** RegularExpression Id. */
  int _DEFAULTPROPERTIES = 25;
  /** RegularExpression Id. */
  int DELEGATE = 26;
  /** RegularExpression Id. */
  int DEPENDSON = 27;
  /** RegularExpression Id. */
  int DEPRECATED = 28;
  /** RegularExpression Id. */
  int DO = 29;
  /** RegularExpression Id. */
  int DONTCOLLAPSECATEGORIES = 30;
  /** RegularExpression Id. */
  int DOTPRODUCT = 31;
  /** RegularExpression Id. */
  int EDFINDABLE = 32;
  /** RegularExpression Id. */
  int EDITCONST = 33;
  /** RegularExpression Id. */
  int EDITINLINE = 34;
  /** RegularExpression Id. */
  int EDITINLINENEW = 35;
  /** RegularExpression Id. */
  int EDITINLINEUSE = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int ENUM = 38;
  /** RegularExpression Id. */
  int EVENT = 39;
  /** RegularExpression Id. */
  int EXEC = 40;
  /** RegularExpression Id. */
  int EXPORT = 41;
  /** RegularExpression Id. */
  int EXPORTSTRUCTS = 42;
  /** RegularExpression Id. */
  int EXTENDS = 43;
  /** RegularExpression Id. */
  int FALSE = 44;
  /** RegularExpression Id. */
  int FINAL = 45;
  /** RegularExpression Id. */
  int FLOAT = 46;
  /** RegularExpression Id. */
  int FOR = 47;
  /** RegularExpression Id. */
  int FOREACH = 48;
  /** RegularExpression Id. */
  int FUNCTION = 49;
  /** RegularExpression Id. */
  int GLOBALCONFIG = 50;
  /** RegularExpression Id. */
  int GOTO = 51;
  /** RegularExpression Id. */
  int GUID = 52;
  /** RegularExpression Id. */
  int HIDECATEGORIES = 53;
  /** RegularExpression Id. */
  int HIDEDROPDOWN = 54;
  /** RegularExpression Id. */
  int IF = 55;
  /** RegularExpression Id. */
  int IGNORES = 56;
  /** RegularExpression Id. */
  int INPUT = 57;
  /** RegularExpression Id. */
  int INSTANCED = 58;
  /** RegularExpression Id. */
  int INT = 59;
  /** RegularExpression Id. */
  int ITERATOR = 60;
  /** RegularExpression Id. */
  int LATENT = 61;
  /** RegularExpression Id. */
  int LOCAL = 62;
  /** RegularExpression Id. */
  int LOCALIZED = 63;
  /** RegularExpression Id. */
  int NAME = 64;
  /** RegularExpression Id. */
  int NATIVE = 65;
  /** RegularExpression Id. */
  int NATIVEREPLICATION = 66;
  /** RegularExpression Id. */
  int NEW = 67;
  /** RegularExpression Id. */
  int NOEDITINLINEW = 68;
  /** RegularExpression Id. */
  int NOEXPORT = 69;
  /** RegularExpression Id. */
  int NONE = 70;
  /** RegularExpression Id. */
  int NOTPLACEABLE = 71;
  /** RegularExpression Id. */
  int OPERATOR = 72;
  /** RegularExpression Id. */
  int OPTIONAL = 73;
  /** RegularExpression Id. */
  int OUT = 74;
  /** RegularExpression Id. */
  int PACKAGE = 75;
  /** RegularExpression Id. */
  int PEROBJECTCONFIG = 76;
  /** RegularExpression Id. */
  int PLACEABLE = 77;
  /** RegularExpression Id. */
  int POSTOPERATOR = 78;
  /** RegularExpression Id. */
  int PREOPERATOR = 79;
  /** RegularExpression Id. */
  int PRIVATE = 80;
  /** RegularExpression Id. */
  int PROTECTED = 81;
  /** RegularExpression Id. */
  int PUBLIC = 82;
  /** RegularExpression Id. */
  int RELIABLE = 83;
  /** RegularExpression Id. */
  int REPLICATION = 84;
  /** RegularExpression Id. */
  int RETURN = 85;
  /** RegularExpression Id. */
  int SAFEREPLACE = 86;
  /** RegularExpression Id. */
  int SHOWCATEGORIES = 87;
  /** RegularExpression Id. */
  int SIMULATED = 88;
  /** RegularExpression Id. */
  int SINGULAR = 89;
  /** RegularExpression Id. */
  int STATE = 90;
  /** RegularExpression Id. */
  int STATIC = 91;
  /** RegularExpression Id. */
  int STRING = 92;
  /** RegularExpression Id. */
  int STRUCT = 93;
  /** RegularExpression Id. */
  int SUPER = 94;
  /** RegularExpression Id. */
  int SWITCH = 95;
  /** RegularExpression Id. */
  int TRANSIENT = 96;
  /** RegularExpression Id. */
  int TRAVEL = 97;
  /** RegularExpression Id. */
  int TRUE = 98;
  /** RegularExpression Id. */
  int UNRELIABLE = 99;
  /** RegularExpression Id. */
  int UNTIL = 100;
  /** RegularExpression Id. */
  int VAR = 101;
  /** RegularExpression Id. */
  int VOID = 102;
  /** RegularExpression Id. */
  int WITHIN = 103;
  /** RegularExpression Id. */
  int WHILE = 104;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 105;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 106;
  /** RegularExpression Id. */
  int HEX_LITERAL = 107;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 108;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 109;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 110;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 111;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 112;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 113;
  /** RegularExpression Id. */
  int NAME_LITERAL = 114;
  /** RegularExpression Id. */
  int STRING_LITERAL = 115;
  /** RegularExpression Id. */
  int IDENTIFIER = 116;
  /** RegularExpression Id. */
  int LETTER = 117;
  /** RegularExpression Id. */
  int PART_LETTER = 118;
  /** RegularExpression Id. */
  int LPAREN = 119;
  /** RegularExpression Id. */
  int RPAREN = 120;
  /** RegularExpression Id. */
  int LBRACE = 121;
  /** RegularExpression Id. */
  int RBRACE = 122;
  /** RegularExpression Id. */
  int LBRACKET = 123;
  /** RegularExpression Id. */
  int RBRACKET = 124;
  /** RegularExpression Id. */
  int SEMICOLON = 125;
  /** RegularExpression Id. */
  int COMMA = 126;
  /** RegularExpression Id. */
  int DOT = 127;
  /** RegularExpression Id. */
  int ASSIGN = 128;
  /** RegularExpression Id. */
  int AT = 129;
  /** RegularExpression Id. */
  int DOLLARS = 130;
  /** RegularExpression Id. */
  int LT = 131;
  /** RegularExpression Id. */
  int BANG = 132;
  /** RegularExpression Id. */
  int TILDE = 133;
  /** RegularExpression Id. */
  int HOOK = 134;
  /** RegularExpression Id. */
  int COLON = 135;
  /** RegularExpression Id. */
  int EQ = 136;
  /** RegularExpression Id. */
  int LE = 137;
  /** RegularExpression Id. */
  int GE = 138;
  /** RegularExpression Id. */
  int NE = 139;
  /** RegularExpression Id. */
  int SC_OR = 140;
  /** RegularExpression Id. */
  int SC_AND = 141;
  /** RegularExpression Id. */
  int INCR = 142;
  /** RegularExpression Id. */
  int DECR = 143;
  /** RegularExpression Id. */
  int PLUS = 144;
  /** RegularExpression Id. */
  int MINUS = 145;
  /** RegularExpression Id. */
  int STAR = 146;
  /** RegularExpression Id. */
  int SLASH = 147;
  /** RegularExpression Id. */
  int BIT_AND = 148;
  /** RegularExpression Id. */
  int BIT_OR = 149;
  /** RegularExpression Id. */
  int XOR = 150;
  /** RegularExpression Id. */
  int REM = 151;
  /** RegularExpression Id. */
  int LSHIFT = 152;
  /** RegularExpression Id. */
  int EXPONENT = 153;
  /** RegularExpression Id. */
  int ATASSIGN = 154;
  /** RegularExpression Id. */
  int DOLLARSASSIGN = 155;
  /** RegularExpression Id. */
  int PLUSASSIGN = 156;
  /** RegularExpression Id. */
  int MINUSASSIGN = 157;
  /** RegularExpression Id. */
  int STARASSIGN = 158;
  /** RegularExpression Id. */
  int SLASHASSIGN = 159;
  /** RegularExpression Id. */
  int ANDASSIGN = 160;
  /** RegularExpression Id. */
  int ORASSIGN = 161;
  /** RegularExpression Id. */
  int XORASSIGN = 162;
  /** RegularExpression Id. */
  int REMASSIGN = 163;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 164;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 165;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 166;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 167;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 168;
  /** RegularExpression Id. */
  int GT = 169;
  /** RegularExpression Id. */
  int STUFF_TO_IGNORE = 171;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "\"abstract\"",
    "\"array\"",
    "\"auto\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"CacheExempt\"",
    "\"case\"",
    "\"class\"",
    "\"ClockwiseFrom\"",
    "\"coerce\"",
    "\"collapsecategories\"",
    "\"config\"",
    "\"const\"",
    "\"continue\"",
    "\"Cross\"",
    "\"default\"",
    "\"defaultproperties\"",
    "\"delegate\"",
    "\"dependsOn\"",
    "\"deprecated\"",
    "\"do\"",
    "\"dontcollapsecategories\"",
    "\"Dot\"",
    "\"edfindable\"",
    "\"editconst\"",
    "\"editinline\"",
    "\"editinlinenew\"",
    "\"editinlineuse\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"exec\"",
    "\"export\"",
    "\"exportstructs\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"float\"",
    "\"for\"",
    "\"ForEach\"",
    "\"function\"",
    "\"globalconfig\"",
    "\"goto\"",
    "\"guid\"",
    "\"hidecategories\"",
    "\"HideDropDown\"",
    "\"if\"",
    "\"ignores\"",
    "\"input\"",
    "\"instanced\"",
    "\"int\"",
    "\"iterator\"",
    "\"latent\"",
    "\"local\"",
    "\"localized\"",
    "\"name\"",
    "\"native\"",
    "\"nativereplication\"",
    "\"new\"",
    "\"noteditinlinenew\"",
    "\"noexport\"",
    "\"none\"",
    "\"notplaceable\"",
    "\"operator\"",
    "\"optional\"",
    "\"out\"",
    "\"package\"",
    "\"perobjectconfig\"",
    "\"placeable\"",
    "\"postOperator\"",
    "\"preOperator\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"reliable\"",
    "\"replication\"",
    "\"return\"",
    "\"safereplace\"",
    "\"showcategories\"",
    "\"simulated\"",
    "\"singular\"",
    "\"state\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"super\"",
    "\"switch\"",
    "\"transient\"",
    "\"travel\"",
    "\"true\"",
    "\"unreliable\"",
    "\"until\"",
    "\"var\"",
    "\"void\"",
    "\"within\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<NAME_LITERAL>",
    "<STRING_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"@\"",
    "\"$\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"**\"",
    "\"@=\"",
    "\"$=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"\\u001a\"",
    "<STUFF_TO_IGNORE>",
    "\"\\\'\"",
    "\"config(file_name)\"",
    "\"hidecategories(category_list)\"",
    "\"#\"",
    "\"\\\\\"",
    "\"`\"",
    "\"?-\"",
    "\"^^\"",
    "\"~=\"",
  };

}
