/* Generated By:JavaCC: Do not edit this line. UnrealScriptParserConstants.java */
package org.unrealscriptsupport.jccparser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UnrealScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int JAVADOC_COMMENT = 5;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int STRING_LITERAL = 11;
  /** RegularExpression Id. */
  int NAME_LITERAL = 14;
  /** RegularExpression Id. */
  int ABSTRACT = 15;
  /** RegularExpression Id. */
  int ARRAY = 16;
  /** RegularExpression Id. */
  int AUTO = 17;
  /** RegularExpression Id. */
  int BOOLEAN = 18;
  /** RegularExpression Id. */
  int BREAK = 19;
  /** RegularExpression Id. */
  int BYTE = 20;
  /** RegularExpression Id. */
  int CACHEEXEMPT = 21;
  /** RegularExpression Id. */
  int CASE = 22;
  /** RegularExpression Id. */
  int CLASS = 23;
  /** RegularExpression Id. */
  int CLOCKWISEFROM = 24;
  /** RegularExpression Id. */
  int COERCE = 25;
  /** RegularExpression Id. */
  int COLLAPSECATEGORIES = 26;
  /** RegularExpression Id. */
  int CONFIG = 27;
  /** RegularExpression Id. */
  int CONST = 28;
  /** RegularExpression Id. */
  int CONTINUE = 29;
  /** RegularExpression Id. */
  int CROSS = 30;
  /** RegularExpression Id. */
  int _DEFAULT = 31;
  /** RegularExpression Id. */
  int _DEFAULTPROPERTIES = 32;
  /** RegularExpression Id. */
  int DELEGATE = 33;
  /** RegularExpression Id. */
  int DEPENDSON = 34;
  /** RegularExpression Id. */
  int DEPRECATED = 35;
  /** RegularExpression Id. */
  int DO = 36;
  /** RegularExpression Id. */
  int DONTCOLLAPSECATEGORIES = 37;
  /** RegularExpression Id. */
  int DOTPRODUCT = 38;
  /** RegularExpression Id. */
  int EDFINDABLE = 39;
  /** RegularExpression Id. */
  int EDITCONST = 40;
  /** RegularExpression Id. */
  int EDITINLINE = 41;
  /** RegularExpression Id. */
  int EDITINLINENEW = 42;
  /** RegularExpression Id. */
  int EDITINLINEUSE = 43;
  /** RegularExpression Id. */
  int ELSE = 44;
  /** RegularExpression Id. */
  int ENUM = 45;
  /** RegularExpression Id. */
  int EVENT = 46;
  /** RegularExpression Id. */
  int EXEC = 47;
  /** RegularExpression Id. */
  int EXPORT = 48;
  /** RegularExpression Id. */
  int EXPORTSTRUCTS = 49;
  /** RegularExpression Id. */
  int EXTENDS = 50;
  /** RegularExpression Id. */
  int FALSE = 51;
  /** RegularExpression Id. */
  int FINAL = 52;
  /** RegularExpression Id. */
  int FLOAT = 53;
  /** RegularExpression Id. */
  int FOR = 54;
  /** RegularExpression Id. */
  int FOREACH = 55;
  /** RegularExpression Id. */
  int FUNCTION = 56;
  /** RegularExpression Id. */
  int GLOBALCONFIG = 57;
  /** RegularExpression Id. */
  int GOTO = 58;
  /** RegularExpression Id. */
  int GUID = 59;
  /** RegularExpression Id. */
  int HIDECATEGORIES = 60;
  /** RegularExpression Id. */
  int HIDEDROPDOWN = 61;
  /** RegularExpression Id. */
  int IF = 62;
  /** RegularExpression Id. */
  int IGNORES = 63;
  /** RegularExpression Id. */
  int INPUT = 64;
  /** RegularExpression Id. */
  int INSTANCED = 65;
  /** RegularExpression Id. */
  int INT = 66;
  /** RegularExpression Id. */
  int ITERATOR = 67;
  /** RegularExpression Id. */
  int LATENT = 68;
  /** RegularExpression Id. */
  int LOCAL = 69;
  /** RegularExpression Id. */
  int LOCALIZED = 70;
  /** RegularExpression Id. */
  int NAME = 71;
  /** RegularExpression Id. */
  int NATIVE = 72;
  /** RegularExpression Id. */
  int NATIVEREPLICATION = 73;
  /** RegularExpression Id. */
  int NEW = 74;
  /** RegularExpression Id. */
  int NOEDITINLINEW = 75;
  /** RegularExpression Id. */
  int NOEXPORT = 76;
  /** RegularExpression Id. */
  int NONE = 77;
  /** RegularExpression Id. */
  int NOTPLACEABLE = 78;
  /** RegularExpression Id. */
  int OPERATOR = 79;
  /** RegularExpression Id. */
  int OPTIONAL = 80;
  /** RegularExpression Id. */
  int OUT = 81;
  /** RegularExpression Id. */
  int PACKAGE = 82;
  /** RegularExpression Id. */
  int PEROBJECTCONFIG = 83;
  /** RegularExpression Id. */
  int PLACEABLE = 84;
  /** RegularExpression Id. */
  int POSTOPERATOR = 85;
  /** RegularExpression Id. */
  int PREOPERATOR = 86;
  /** RegularExpression Id. */
  int PRIVATE = 87;
  /** RegularExpression Id. */
  int PROTECTED = 88;
  /** RegularExpression Id. */
  int PUBLIC = 89;
  /** RegularExpression Id. */
  int RELIABLE = 90;
  /** RegularExpression Id. */
  int REPLICATION = 91;
  /** RegularExpression Id. */
  int RETURN = 92;
  /** RegularExpression Id. */
  int SAFEREPLACE = 93;
  /** RegularExpression Id. */
  int SHOWCATEGORIES = 94;
  /** RegularExpression Id. */
  int SIMULATED = 95;
  /** RegularExpression Id. */
  int SINGULAR = 96;
  /** RegularExpression Id. */
  int STATE = 97;
  /** RegularExpression Id. */
  int STATIC = 98;
  /** RegularExpression Id. */
  int STRING = 99;
  /** RegularExpression Id. */
  int STRUCT = 100;
  /** RegularExpression Id. */
  int STRUCTDEFAULTPROPERTIES = 101;
  /** RegularExpression Id. */
  int SUPER = 102;
  /** RegularExpression Id. */
  int SWITCH = 103;
  /** RegularExpression Id. */
  int TRANSIENT = 104;
  /** RegularExpression Id. */
  int TRAVEL = 105;
  /** RegularExpression Id. */
  int TRUE = 106;
  /** RegularExpression Id. */
  int UNRELIABLE = 107;
  /** RegularExpression Id. */
  int UNTIL = 108;
  /** RegularExpression Id. */
  int VAR = 109;
  /** RegularExpression Id. */
  int VOID = 110;
  /** RegularExpression Id. */
  int WITHIN = 111;
  /** RegularExpression Id. */
  int WHILE = 112;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 113;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 114;
  /** RegularExpression Id. */
  int HEX_LITERAL = 115;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 116;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 117;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 118;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 119;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 120;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 121;
  /** RegularExpression Id. */
  int IDENTIFIER = 122;
  /** RegularExpression Id. */
  int LETTER = 123;
  /** RegularExpression Id. */
  int PART_LETTER = 124;
  /** RegularExpression Id. */
  int LPAREN = 125;
  /** RegularExpression Id. */
  int RPAREN = 126;
  /** RegularExpression Id. */
  int LBRACE = 127;
  /** RegularExpression Id. */
  int RBRACE = 128;
  /** RegularExpression Id. */
  int LBRACKET = 129;
  /** RegularExpression Id. */
  int RBRACKET = 130;
  /** RegularExpression Id. */
  int SEMICOLON = 131;
  /** RegularExpression Id. */
  int COMMA = 132;
  /** RegularExpression Id. */
  int DOT = 133;
  /** RegularExpression Id. */
  int ASSIGN = 134;
  /** RegularExpression Id. */
  int AT = 135;
  /** RegularExpression Id. */
  int DOLLARS = 136;
  /** RegularExpression Id. */
  int LT = 137;
  /** RegularExpression Id. */
  int BANG = 138;
  /** RegularExpression Id. */
  int TILDE = 139;
  /** RegularExpression Id. */
  int HOOK = 140;
  /** RegularExpression Id. */
  int COLON = 141;
  /** RegularExpression Id. */
  int EQ = 142;
  /** RegularExpression Id. */
  int LE = 143;
  /** RegularExpression Id. */
  int GE = 144;
  /** RegularExpression Id. */
  int NE = 145;
  /** RegularExpression Id. */
  int SC_OR = 146;
  /** RegularExpression Id. */
  int SC_AND = 147;
  /** RegularExpression Id. */
  int INCR = 148;
  /** RegularExpression Id. */
  int DECR = 149;
  /** RegularExpression Id. */
  int PLUS = 150;
  /** RegularExpression Id. */
  int MINUS = 151;
  /** RegularExpression Id. */
  int STAR = 152;
  /** RegularExpression Id. */
  int SLASH = 153;
  /** RegularExpression Id. */
  int BIT_AND = 154;
  /** RegularExpression Id. */
  int BIT_OR = 155;
  /** RegularExpression Id. */
  int XOR = 156;
  /** RegularExpression Id. */
  int REM = 157;
  /** RegularExpression Id. */
  int LSHIFT = 158;
  /** RegularExpression Id. */
  int EXPONENT = 159;
  /** RegularExpression Id. */
  int ATASSIGN = 160;
  /** RegularExpression Id. */
  int DOLLARSASSIGN = 161;
  /** RegularExpression Id. */
  int PLUSASSIGN = 162;
  /** RegularExpression Id. */
  int MINUSASSIGN = 163;
  /** RegularExpression Id. */
  int STARASSIGN = 164;
  /** RegularExpression Id. */
  int SLASHASSIGN = 165;
  /** RegularExpression Id. */
  int ANDASSIGN = 166;
  /** RegularExpression Id. */
  int ORASSIGN = 167;
  /** RegularExpression Id. */
  int XORASSIGN = 168;
  /** RegularExpression Id. */
  int REMASSIGN = 169;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 170;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 171;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 172;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 173;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 174;
  /** RegularExpression Id. */
  int GT = 175;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_JAVADOC_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_STRING_LITERAL = 3;
  /** Lexical state. */
  int IN_NAME_LITERAL = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"\\\"\"",
    "<token of kind 10>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<token of kind 13>",
    "\"\\\'\"",
    "\"abstract\"",
    "\"array\"",
    "\"auto\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"cacheexempt\"",
    "\"case\"",
    "\"class\"",
    "\"clockwisefrom\"",
    "\"coerce\"",
    "\"collapsecategories\"",
    "\"config\"",
    "\"const\"",
    "\"continue\"",
    "\"cross\"",
    "\"default\"",
    "\"defaultproperties\"",
    "\"delegate\"",
    "\"dependsOn\"",
    "\"deprecated\"",
    "\"do\"",
    "\"dontcollapsecategories\"",
    "\"dot\"",
    "\"edfindable\"",
    "\"editconst\"",
    "\"editinline\"",
    "\"editinlinenew\"",
    "\"editinlineuse\"",
    "\"else\"",
    "\"enum\"",
    "\"event\"",
    "\"exec\"",
    "\"export\"",
    "\"exportstructs\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"function\"",
    "\"globalconfig\"",
    "\"goto\"",
    "\"guid\"",
    "\"hidecategories\"",
    "\"hidedropdown\"",
    "\"if\"",
    "\"ignores\"",
    "\"input\"",
    "\"instanced\"",
    "\"int\"",
    "\"iterator\"",
    "\"latent\"",
    "\"local\"",
    "\"localized\"",
    "\"name\"",
    "\"native\"",
    "\"nativereplication\"",
    "\"new\"",
    "\"noteditinlinenew\"",
    "\"noexport\"",
    "\"none\"",
    "\"notplaceable\"",
    "\"operator\"",
    "\"optional\"",
    "\"out\"",
    "\"package\"",
    "\"perobjectconfig\"",
    "\"placeable\"",
    "\"postoperator\"",
    "\"preoperator\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"reliable\"",
    "\"replication\"",
    "\"return\"",
    "\"safereplace\"",
    "\"showcategories\"",
    "\"simulated\"",
    "\"singular\"",
    "\"state\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"structdefaultproperties\"",
    "\"super\"",
    "\"switch\"",
    "\"transient\"",
    "\"travel\"",
    "\"true\"",
    "\"unreliable\"",
    "\"until\"",
    "\"var\"",
    "\"void\"",
    "\"within\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"@\"",
    "\"$\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"**\"",
    "\"@=\"",
    "\"$=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "\"#\"",
    "\"\\\\\"",
    "\"`\"",
    "\"?-\"",
    "\"^^\"",
    "\"~=\"",
  };

}
