/* Generated By:JavaCC: Do not edit this line. UnrealScriptParserConstants.java */
package org.unrealscriptsupport.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UnrealScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 4;
  /** RegularExpression Id. */
  int COMPILER_DIRECTIVE = 5;
  /** RegularExpression Id. */
  int PREPROCESSOR_DIRECTIVE = 6;
  /** RegularExpression Id. */
  int JAVADOC_COMMENT = 7;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 8;
  /** RegularExpression Id. */
  int STRING_LITERAL = 13;
  /** RegularExpression Id. */
  int NAME_LITERAL = 16;
  /** RegularExpression Id. */
  int ABSTRACT = 17;
  /** RegularExpression Id. */
  int ARRAY = 18;
  /** RegularExpression Id. */
  int AUTO = 19;
  /** RegularExpression Id. */
  int BEGIN = 20;
  /** RegularExpression Id. */
  int BOOLEAN = 21;
  /** RegularExpression Id. */
  int BREAK = 22;
  /** RegularExpression Id. */
  int BYTE = 23;
  /** RegularExpression Id. */
  int CACHEEXEMPT = 24;
  /** RegularExpression Id. */
  int CASE = 25;
  /** RegularExpression Id. */
  int CLASS = 26;
  /** RegularExpression Id. */
  int CLOCKWISEFROM = 27;
  /** RegularExpression Id. */
  int COERCE = 28;
  /** RegularExpression Id. */
  int COLLAPSECATEGORIES = 29;
  /** RegularExpression Id. */
  int CONFIG = 30;
  /** RegularExpression Id. */
  int CONST = 31;
  /** RegularExpression Id. */
  int CONTINUE = 32;
  /** RegularExpression Id. */
  int CPPTEXT = 33;
  /** RegularExpression Id. */
  int CROSS = 34;
  /** RegularExpression Id. */
  int _DEFAULT = 35;
  /** RegularExpression Id. */
  int _DEFAULTPROPERTIES = 36;
  /** RegularExpression Id. */
  int DELEGATE = 37;
  /** RegularExpression Id. */
  int DEPENDSON = 38;
  /** RegularExpression Id. */
  int DEPRECATED = 39;
  /** RegularExpression Id. */
  int DO = 40;
  /** RegularExpression Id. */
  int DONTCOLLAPSECATEGORIES = 41;
  /** RegularExpression Id. */
  int DOTPRODUCT = 42;
  /** RegularExpression Id. */
  int EDFINDABLE = 43;
  /** RegularExpression Id. */
  int EDITCONST = 44;
  /** RegularExpression Id. */
  int EDITINLINE = 45;
  /** RegularExpression Id. */
  int EDITINLINENEW = 46;
  /** RegularExpression Id. */
  int EDITINLINEUSE = 47;
  /** RegularExpression Id. */
  int ELSE = 48;
  /** RegularExpression Id. */
  int END = 49;
  /** RegularExpression Id. */
  int ENUM = 50;
  /** RegularExpression Id. */
  int EVENT = 51;
  /** RegularExpression Id. */
  int EXEC = 52;
  /** RegularExpression Id. */
  int EXPORT = 53;
  /** RegularExpression Id. */
  int EXPORTSTRUCTS = 54;
  /** RegularExpression Id. */
  int EXTENDS = 55;
  /** RegularExpression Id. */
  int FALSE = 56;
  /** RegularExpression Id. */
  int FINAL = 57;
  /** RegularExpression Id. */
  int FLOAT = 58;
  /** RegularExpression Id. */
  int FOR = 59;
  /** RegularExpression Id. */
  int FOREACH = 60;
  /** RegularExpression Id. */
  int FUNCTION = 61;
  /** RegularExpression Id. */
  int GLOBAL = 62;
  /** RegularExpression Id. */
  int GLOBALCONFIG = 63;
  /** RegularExpression Id. */
  int GOTO = 64;
  /** RegularExpression Id. */
  int GUID = 65;
  /** RegularExpression Id. */
  int HIDECATEGORIES = 66;
  /** RegularExpression Id. */
  int HIDEDROPDOWN = 67;
  /** RegularExpression Id. */
  int IF = 68;
  /** RegularExpression Id. */
  int IGNORES = 69;
  /** RegularExpression Id. */
  int INPUT = 70;
  /** RegularExpression Id. */
  int INSTANCED = 71;
  /** RegularExpression Id. */
  int INT = 72;
  /** RegularExpression Id. */
  int ITERATOR = 73;
  /** RegularExpression Id. */
  int LATENT = 74;
  /** RegularExpression Id. */
  int LOCAL = 75;
  /** RegularExpression Id. */
  int LOCALIZED = 76;
  /** RegularExpression Id. */
  int NAME = 77;
  /** RegularExpression Id. */
  int NATIVE = 78;
  /** RegularExpression Id. */
  int NATIVEREPLICATION = 79;
  /** RegularExpression Id. */
  int NEW = 80;
  /** RegularExpression Id. */
  int NOEDITINLINEW = 81;
  /** RegularExpression Id. */
  int NOEXPORT = 82;
  /** RegularExpression Id. */
  int NONE = 83;
  /** RegularExpression Id. */
  int NOTPLACEABLE = 84;
  /** RegularExpression Id. */
  int OBJECT = 85;
  /** RegularExpression Id. */
  int OPERATOR = 86;
  /** RegularExpression Id. */
  int OPTIONAL = 87;
  /** RegularExpression Id. */
  int OUT = 88;
  /** RegularExpression Id. */
  int PACKAGE = 89;
  /** RegularExpression Id. */
  int PEROBJECTCONFIG = 90;
  /** RegularExpression Id. */
  int PLACEABLE = 91;
  /** RegularExpression Id. */
  int POSTOPERATOR = 92;
  /** RegularExpression Id. */
  int PREOPERATOR = 93;
  /** RegularExpression Id. */
  int PRIVATE = 94;
  /** RegularExpression Id. */
  int PROTECTED = 95;
  /** RegularExpression Id. */
  int PUBLIC = 96;
  /** RegularExpression Id. */
  int RELIABLE = 97;
  /** RegularExpression Id. */
  int REPLICATION = 98;
  /** RegularExpression Id. */
  int RETURN = 99;
  /** RegularExpression Id. */
  int SAFEREPLACE = 100;
  /** RegularExpression Id. */
  int SHOWCATEGORIES = 101;
  /** RegularExpression Id. */
  int SIMULATED = 102;
  /** RegularExpression Id. */
  int SINGULAR = 103;
  /** RegularExpression Id. */
  int STATE = 104;
  /** RegularExpression Id. */
  int STATIC = 105;
  /** RegularExpression Id. */
  int STRING = 106;
  /** RegularExpression Id. */
  int STRUCT = 107;
  /** RegularExpression Id. */
  int STRUCTDEFAULTPROPERTIES = 108;
  /** RegularExpression Id. */
  int SUPER = 109;
  /** RegularExpression Id. */
  int SWITCH = 110;
  /** RegularExpression Id. */
  int TRANSIENT = 111;
  /** RegularExpression Id. */
  int TRAVEL = 112;
  /** RegularExpression Id. */
  int TRUE = 113;
  /** RegularExpression Id. */
  int UNRELIABLE = 114;
  /** RegularExpression Id. */
  int UNTIL = 115;
  /** RegularExpression Id. */
  int VAR = 116;
  /** RegularExpression Id. */
  int VOID = 117;
  /** RegularExpression Id. */
  int WITHIN = 118;
  /** RegularExpression Id. */
  int WHILE = 119;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 120;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 121;
  /** RegularExpression Id. */
  int HEX_LITERAL = 122;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 123;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 124;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 125;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 126;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 127;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 128;
  /** RegularExpression Id. */
  int IDENTIFIER = 129;
  /** RegularExpression Id. */
  int LETTER = 130;
  /** RegularExpression Id. */
  int PART_LETTER = 131;
  /** RegularExpression Id. */
  int LPAREN = 132;
  /** RegularExpression Id. */
  int RPAREN = 133;
  /** RegularExpression Id. */
  int LBRACE = 134;
  /** RegularExpression Id. */
  int RBRACE = 135;
  /** RegularExpression Id. */
  int LBRACKET = 136;
  /** RegularExpression Id. */
  int RBRACKET = 137;
  /** RegularExpression Id. */
  int SEMICOLON = 138;
  /** RegularExpression Id. */
  int COMMA = 139;
  /** RegularExpression Id. */
  int DOT = 140;
  /** RegularExpression Id. */
  int ASSIGN = 141;
  /** RegularExpression Id. */
  int AT = 142;
  /** RegularExpression Id. */
  int DOLLARS = 143;
  /** RegularExpression Id. */
  int LT = 144;
  /** RegularExpression Id. */
  int BANG = 145;
  /** RegularExpression Id. */
  int TILDE = 146;
  /** RegularExpression Id. */
  int HOOK = 147;
  /** RegularExpression Id. */
  int COLON = 148;
  /** RegularExpression Id. */
  int EQ = 149;
  /** RegularExpression Id. */
  int LE = 150;
  /** RegularExpression Id. */
  int GE = 151;
  /** RegularExpression Id. */
  int NE = 152;
  /** RegularExpression Id. */
  int SC_OR = 153;
  /** RegularExpression Id. */
  int SC_AND = 154;
  /** RegularExpression Id. */
  int INCR = 155;
  /** RegularExpression Id. */
  int DECR = 156;
  /** RegularExpression Id. */
  int PLUS = 157;
  /** RegularExpression Id. */
  int MINUS = 158;
  /** RegularExpression Id. */
  int STAR = 159;
  /** RegularExpression Id. */
  int SLASH = 160;
  /** RegularExpression Id. */
  int BIT_AND = 161;
  /** RegularExpression Id. */
  int BIT_OR = 162;
  /** RegularExpression Id. */
  int XOR = 163;
  /** RegularExpression Id. */
  int REM = 164;
  /** RegularExpression Id. */
  int LSHIFT = 165;
  /** RegularExpression Id. */
  int EXPONENT = 166;
  /** RegularExpression Id. */
  int ATASSIGN = 167;
  /** RegularExpression Id. */
  int DOLLARSASSIGN = 168;
  /** RegularExpression Id. */
  int PLUSASSIGN = 169;
  /** RegularExpression Id. */
  int MINUSASSIGN = 170;
  /** RegularExpression Id. */
  int STARASSIGN = 171;
  /** RegularExpression Id. */
  int SLASHASSIGN = 172;
  /** RegularExpression Id. */
  int ANDASSIGN = 173;
  /** RegularExpression Id. */
  int ORASSIGN = 174;
  /** RegularExpression Id. */
  int XORASSIGN = 175;
  /** RegularExpression Id. */
  int REMASSIGN = 176;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 177;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 178;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 179;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 180;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 181;
  /** RegularExpression Id. */
  int GT = 182;
  /** RegularExpression Id. */
  int ALL = 183;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_JAVADOC_COMMENT = 1;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 2;
  /** Lexical state. */
  int IN_STRING_LITERAL = 3;
  /** Lexical state. */
  int IN_NAME_LITERAL = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<token of kind 2>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "<COMPILER_DIRECTIVE>",
    "<PREPROCESSOR_DIRECTIVE>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 9>",
    "<token of kind 10>",
    "\"\\\"\"",
    "<token of kind 12>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<token of kind 15>",
    "\"\\\'\"",
    "\"abstract\"",
    "\"array\"",
    "\"auto\"",
    "\"begin\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"cacheexempt\"",
    "\"case\"",
    "\"class\"",
    "\"clockwisefrom\"",
    "\"coerce\"",
    "\"collapsecategories\"",
    "\"config\"",
    "\"const\"",
    "\"continue\"",
    "\"cpptext\"",
    "\"cross\"",
    "\"default\"",
    "\"defaultproperties\"",
    "\"delegate\"",
    "\"dependsOn\"",
    "\"deprecated\"",
    "\"do\"",
    "\"dontcollapsecategories\"",
    "\"dot\"",
    "\"edfindable\"",
    "\"editconst\"",
    "\"editinline\"",
    "\"editinlinenew\"",
    "\"editinlineuse\"",
    "\"else\"",
    "\"end\"",
    "\"enum\"",
    "\"event\"",
    "\"exec\"",
    "\"export\"",
    "\"exportstructs\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"function\"",
    "\"global\"",
    "\"globalconfig\"",
    "\"goto\"",
    "\"guid\"",
    "\"hidecategories\"",
    "\"hidedropdown\"",
    "\"if\"",
    "\"ignores\"",
    "\"input\"",
    "\"instanced\"",
    "\"int\"",
    "\"iterator\"",
    "\"latent\"",
    "\"local\"",
    "\"localized\"",
    "\"name\"",
    "\"native\"",
    "\"nativereplication\"",
    "\"new\"",
    "\"noteditinlinenew\"",
    "\"noexport\"",
    "\"none\"",
    "\"notplaceable\"",
    "\"object\"",
    "\"operator\"",
    "\"optional\"",
    "\"out\"",
    "\"package\"",
    "\"perobjectconfig\"",
    "\"placeable\"",
    "\"postoperator\"",
    "\"preoperator\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"reliable\"",
    "\"replication\"",
    "\"return\"",
    "\"safereplace\"",
    "\"showcategories\"",
    "\"simulated\"",
    "\"singular\"",
    "\"state\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"structdefaultproperties\"",
    "\"super\"",
    "\"switch\"",
    "\"transient\"",
    "\"travel\"",
    "\"true\"",
    "\"unreliable\"",
    "\"until\"",
    "\"var\"",
    "\"void\"",
    "\"within\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"@\"",
    "\"$\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"**\"",
    "\"@=\"",
    "\"$=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "<ALL>",
  };

}
