/* Generated By:JavaCC: Do not edit this line. UnrealScriptParserConstants.java */
package org.unrealscriptsupport.jcclexer;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface UnrealScriptParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 2;
  /** RegularExpression Id. */
  int COMPILER_DIRECTIVE = 3;
  /** RegularExpression Id. */
  int PREPROCESSOR_DIRECTIVE = 4;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 6;
  /** RegularExpression Id. */
  int JAVADOC_COMMENT = 9;
  /** RegularExpression Id. */
  int STRING_LITERAL = 13;
  /** RegularExpression Id. */
  int NAME_LITERAL = 16;
  /** RegularExpression Id. */
  int CPPCODE = 19;
  /** RegularExpression Id. */
  int ABSTRACT = 20;
  /** RegularExpression Id. */
  int ALLOWABSTRACT = 21;
  /** RegularExpression Id. */
  int ARRAY = 22;
  /** RegularExpression Id. */
  int AUTO = 23;
  /** RegularExpression Id. */
  int BEGIN = 24;
  /** RegularExpression Id. */
  int BOOLEAN = 25;
  /** RegularExpression Id. */
  int BREAK = 26;
  /** RegularExpression Id. */
  int BYTE = 27;
  /** RegularExpression Id. */
  int CACHE = 28;
  /** RegularExpression Id. */
  int CACHEEXEMPT = 29;
  /** RegularExpression Id. */
  int CASE = 30;
  /** RegularExpression Id. */
  int CLASS = 31;
  /** RegularExpression Id. */
  int CLOCKWISEFROM = 32;
  /** RegularExpression Id. */
  int COERCE = 33;
  /** RegularExpression Id. */
  int COLLAPSECATEGORIES = 34;
  /** RegularExpression Id. */
  int CONFIG = 35;
  /** RegularExpression Id. */
  int CONST = 36;
  /** RegularExpression Id. */
  int CONTINUE = 37;
  /** RegularExpression Id. */
  int CROSS = 38;
  /** RegularExpression Id. */
  int DATABINDING = 39;
  /** RegularExpression Id. */
  int _DEFAULT = 40;
  /** RegularExpression Id. */
  int _DEFAULTPROPERTIES = 41;
  /** RegularExpression Id. */
  int DELEGATE = 42;
  /** RegularExpression Id. */
  int DEPENDSON = 43;
  /** RegularExpression Id. */
  int DEPRECATED = 44;
  /** RegularExpression Id. */
  int DO = 45;
  /** RegularExpression Id. */
  int DONTCOLLAPSECATEGORIES = 46;
  /** RegularExpression Id. */
  int DOTPRODUCT = 47;
  /** RegularExpression Id. */
  int DUPLICATETRANSIENT = 48;
  /** RegularExpression Id. */
  int EDFINDABLE = 49;
  /** RegularExpression Id. */
  int EDITCONST = 50;
  /** RegularExpression Id. */
  int EDITCONSTARRAY = 51;
  /** RegularExpression Id. */
  int EDITFIXEDSIZE = 52;
  /** RegularExpression Id. */
  int EDITINLINE = 53;
  /** RegularExpression Id. */
  int EDITINLINENEW = 54;
  /** RegularExpression Id. */
  int EDITINLINEUSE = 55;
  /** RegularExpression Id. */
  int EDITORONLY = 56;
  /** RegularExpression Id. */
  int ELSE = 57;
  /** RegularExpression Id. */
  int END = 58;
  /** RegularExpression Id. */
  int ENUM = 59;
  /** RegularExpression Id. */
  int EVENT = 60;
  /** RegularExpression Id. */
  int EXEC = 61;
  /** RegularExpression Id. */
  int EXPORT = 62;
  /** RegularExpression Id. */
  int EXPORTSTRUCTS = 63;
  /** RegularExpression Id. */
  int EXTENDS = 64;
  /** RegularExpression Id. */
  int FALSE = 65;
  /** RegularExpression Id. */
  int FINAL = 66;
  /** RegularExpression Id. */
  int FLOAT = 67;
  /** RegularExpression Id. */
  int FOR = 68;
  /** RegularExpression Id. */
  int FOREACH = 69;
  /** RegularExpression Id. */
  int FUNCTION = 70;
  /** RegularExpression Id. */
  int GLOBAL = 71;
  /** RegularExpression Id. */
  int GLOBALCONFIG = 72;
  /** RegularExpression Id. */
  int GOTO = 73;
  /** RegularExpression Id. */
  int GUID = 74;
  /** RegularExpression Id. */
  int HIDECATEGORIES = 75;
  /** RegularExpression Id. */
  int HIDEDROPDOWN = 76;
  /** RegularExpression Id. */
  int IF = 77;
  /** RegularExpression Id. */
  int IGNORES = 78;
  /** RegularExpression Id. */
  int INIT = 79;
  /** RegularExpression Id. */
  int INPUT = 80;
  /** RegularExpression Id. */
  int INSTANCED = 81;
  /** RegularExpression Id. */
  int INT = 82;
  /** RegularExpression Id. */
  int INTERP = 83;
  /** RegularExpression Id. */
  int ITERATOR = 84;
  /** RegularExpression Id. */
  int LATENT = 85;
  /** RegularExpression Id. */
  int LOCAL = 86;
  /** RegularExpression Id. */
  int LOCALIZED = 87;
  /** RegularExpression Id. */
  int NAME = 88;
  /** RegularExpression Id. */
  int NATIVE = 89;
  /** RegularExpression Id. */
  int NATIVEREPLICATION = 90;
  /** RegularExpression Id. */
  int NEW = 91;
  /** RegularExpression Id. */
  int NOCLEAR = 92;
  /** RegularExpression Id. */
  int NOEDITINLINEW = 93;
  /** RegularExpression Id. */
  int NOEXPORT = 94;
  /** RegularExpression Id. */
  int NOIMPORT = 95;
  /** RegularExpression Id. */
  int NONE = 96;
  /** RegularExpression Id. */
  int NONTRANSACTIONAL = 97;
  /** RegularExpression Id. */
  int NOTFORCONSOLE = 98;
  /** RegularExpression Id. */
  int NOTPLACEABLE = 99;
  /** RegularExpression Id. */
  int OBJECT = 100;
  /** RegularExpression Id. */
  int OPERATOR = 101;
  /** RegularExpression Id. */
  int OPTIONAL = 102;
  /** RegularExpression Id. */
  int OUT = 103;
  /** RegularExpression Id. */
  int PACKAGE = 104;
  /** RegularExpression Id. */
  int PEROBJECTCONFIG = 105;
  /** RegularExpression Id. */
  int PLACEABLE = 106;
  /** RegularExpression Id. */
  int POINTER = 107;
  /** RegularExpression Id. */
  int POSTOPERATOR = 108;
  /** RegularExpression Id. */
  int PREOPERATOR = 109;
  /** RegularExpression Id. */
  int PRIVATE = 110;
  /** RegularExpression Id. */
  int PROTECTED = 111;
  /** RegularExpression Id. */
  int PUBLIC = 112;
  /** RegularExpression Id. */
  int RELIABLE = 113;
  /** RegularExpression Id. */
  int REPLICATION = 114;
  /** RegularExpression Id. */
  int REPNOTIFY = 115;
  /** RegularExpression Id. */
  int REPRETRY = 116;
  /** RegularExpression Id. */
  int RETURN = 117;
  /** RegularExpression Id. */
  int SAFEREPLACE = 118;
  /** RegularExpression Id. */
  int SHOWCATEGORIES = 119;
  /** RegularExpression Id. */
  int SIMULATED = 120;
  /** RegularExpression Id. */
  int SINGULAR = 121;
  /** RegularExpression Id. */
  int _SKIP = 122;
  /** RegularExpression Id. */
  int STATE = 123;
  /** RegularExpression Id. */
  int STATIC = 124;
  /** RegularExpression Id. */
  int STRING = 125;
  /** RegularExpression Id. */
  int STRUCT = 126;
  /** RegularExpression Id. */
  int STRUCTDEFAULTPROPERTIES = 127;
  /** RegularExpression Id. */
  int SUPER = 128;
  /** RegularExpression Id. */
  int SWITCH = 129;
  /** RegularExpression Id. */
  int TRANSIENT = 130;
  /** RegularExpression Id. */
  int TRAVEL = 131;
  /** RegularExpression Id. */
  int TRUE = 132;
  /** RegularExpression Id. */
  int UNRELIABLE = 133;
  /** RegularExpression Id. */
  int UNTIL = 134;
  /** RegularExpression Id. */
  int VAR = 135;
  /** RegularExpression Id. */
  int VIRTUAL = 136;
  /** RegularExpression Id. */
  int VOID = 137;
  /** RegularExpression Id. */
  int WITHIN = 138;
  /** RegularExpression Id. */
  int WHILE = 139;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 140;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 141;
  /** RegularExpression Id. */
  int HEX_LITERAL = 142;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 143;
  /** RegularExpression Id. */
  int FLOATING_POINT_LITERAL = 144;
  /** RegularExpression Id. */
  int DECIMAL_FLOATING_POINT_LITERAL = 145;
  /** RegularExpression Id. */
  int DECIMAL_EXPONENT = 146;
  /** RegularExpression Id. */
  int HEXADECIMAL_FLOATING_POINT_LITERAL = 147;
  /** RegularExpression Id. */
  int HEXADECIMAL_EXPONENT = 148;
  /** RegularExpression Id. */
  int IDENTIFIER = 149;
  /** RegularExpression Id. */
  int LETTER = 150;
  /** RegularExpression Id. */
  int PART_LETTER = 151;
  /** RegularExpression Id. */
  int LPAREN = 152;
  /** RegularExpression Id. */
  int RPAREN = 153;
  /** RegularExpression Id. */
  int LBRACE = 154;
  /** RegularExpression Id. */
  int RBRACE = 155;
  /** RegularExpression Id. */
  int LBRACKET = 156;
  /** RegularExpression Id. */
  int RBRACKET = 157;
  /** RegularExpression Id. */
  int SEMICOLON = 158;
  /** RegularExpression Id. */
  int COMMA = 159;
  /** RegularExpression Id. */
  int DOT = 160;
  /** RegularExpression Id. */
  int ASSIGN = 161;
  /** RegularExpression Id. */
  int AT = 162;
  /** RegularExpression Id. */
  int DOLLARS = 163;
  /** RegularExpression Id. */
  int LT = 164;
  /** RegularExpression Id. */
  int BANG = 165;
  /** RegularExpression Id. */
  int TILDE = 166;
  /** RegularExpression Id. */
  int HOOK = 167;
  /** RegularExpression Id. */
  int COLON = 168;
  /** RegularExpression Id. */
  int EQ = 169;
  /** RegularExpression Id. */
  int LE = 170;
  /** RegularExpression Id. */
  int GE = 171;
  /** RegularExpression Id. */
  int NE = 172;
  /** RegularExpression Id. */
  int SC_OR = 173;
  /** RegularExpression Id. */
  int SC_AND = 174;
  /** RegularExpression Id. */
  int INCR = 175;
  /** RegularExpression Id. */
  int DECR = 176;
  /** RegularExpression Id. */
  int PLUS = 177;
  /** RegularExpression Id. */
  int MINUS = 178;
  /** RegularExpression Id. */
  int STAR = 179;
  /** RegularExpression Id. */
  int SLASH = 180;
  /** RegularExpression Id. */
  int BIT_AND = 181;
  /** RegularExpression Id. */
  int BIT_OR = 182;
  /** RegularExpression Id. */
  int XOR = 183;
  /** RegularExpression Id. */
  int REM = 184;
  /** RegularExpression Id. */
  int LSHIFT = 185;
  /** RegularExpression Id. */
  int EXPONENT = 186;
  /** RegularExpression Id. */
  int ATASSIGN = 187;
  /** RegularExpression Id. */
  int DOLLARSASSIGN = 188;
  /** RegularExpression Id. */
  int PLUSASSIGN = 189;
  /** RegularExpression Id. */
  int MINUSASSIGN = 190;
  /** RegularExpression Id. */
  int STARASSIGN = 191;
  /** RegularExpression Id. */
  int SLASHASSIGN = 192;
  /** RegularExpression Id. */
  int ANDASSIGN = 193;
  /** RegularExpression Id. */
  int ORASSIGN = 194;
  /** RegularExpression Id. */
  int XORASSIGN = 195;
  /** RegularExpression Id. */
  int REMASSIGN = 196;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 197;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 198;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 199;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFT = 200;
  /** RegularExpression Id. */
  int RSIGNEDSHIFT = 201;
  /** RegularExpression Id. */
  int GT = 202;
  /** RegularExpression Id. */
  int ALL = 203;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_JAVADOC_COMMENT = 2;
  /** Lexical state. */
  int IN_STRING_LITERAL = 3;
  /** Lexical state. */
  int IN_NAME_LITERAL = 4;
  /** Lexical state. */
  int IN_CPPCODE = 5;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<SINGLE_LINE_COMMENT>",
    "<COMPILER_DIRECTIVE>",
    "<PREPROCESSOR_DIRECTIVE>",
    "<token of kind 5>",
    "\"*/\"",
    "<token of kind 7>",
    "<token of kind 8>",
    "\"*/\"",
    "<token of kind 10>",
    "\"\\\"\"",
    "<token of kind 12>",
    "\"\\\"\"",
    "\"\\\'\"",
    "<token of kind 15>",
    "\"\\\'\"",
    "<token of kind 17>",
    "<token of kind 18>",
    "\"}\"",
    "\"abstract\"",
    "\"allowabstract\"",
    "\"array\"",
    "\"auto\"",
    "\"begin\"",
    "\"bool\"",
    "\"break\"",
    "\"byte\"",
    "\"cache\"",
    "\"cacheexempt\"",
    "\"case\"",
    "\"class\"",
    "\"clockwisefrom\"",
    "\"coerce\"",
    "\"collapsecategories\"",
    "\"config\"",
    "\"const\"",
    "\"continue\"",
    "\"cross\"",
    "\"databinding\"",
    "\"default\"",
    "\"defaultproperties\"",
    "\"delegate\"",
    "\"dependson\"",
    "\"deprecated\"",
    "\"do\"",
    "\"dontcollapsecategories\"",
    "\"dot\"",
    "\"duplicatetransient\"",
    "\"edfindable\"",
    "\"editconst\"",
    "\"editconstarray\"",
    "\"editfixedsize\"",
    "\"editinline\"",
    "\"editinlinenew\"",
    "\"editinlineuse\"",
    "\"editoronly\"",
    "\"else\"",
    "\"end\"",
    "\"enum\"",
    "\"event\"",
    "\"exec\"",
    "\"export\"",
    "\"exportstructs\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"float\"",
    "\"for\"",
    "\"foreach\"",
    "\"function\"",
    "\"global\"",
    "\"globalconfig\"",
    "\"goto\"",
    "\"guid\"",
    "\"hidecategories\"",
    "\"hidedropdown\"",
    "\"if\"",
    "\"ignores\"",
    "\"init\"",
    "\"input\"",
    "\"instanced\"",
    "\"int\"",
    "\"interp\"",
    "\"iterator\"",
    "\"latent\"",
    "\"local\"",
    "\"localized\"",
    "\"name\"",
    "\"native\"",
    "\"nativereplication\"",
    "\"new\"",
    "\"noclear\"",
    "\"noteditinlinenew\"",
    "\"noexport\"",
    "\"noimport\"",
    "\"none\"",
    "\"nontransactional\"",
    "\"notforconsole\"",
    "\"notplaceable\"",
    "\"object\"",
    "\"operator\"",
    "\"optional\"",
    "\"out\"",
    "\"package\"",
    "\"perobjectconfig\"",
    "\"placeable\"",
    "\"pointer\"",
    "\"postoperator\"",
    "\"preoperator\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"reliable\"",
    "\"replication\"",
    "\"repnotify\"",
    "\"repretry\"",
    "\"return\"",
    "\"safereplace\"",
    "\"showcategories\"",
    "\"simulated\"",
    "\"singular\"",
    "\"skip\"",
    "\"state\"",
    "\"static\"",
    "\"string\"",
    "\"struct\"",
    "\"structdefaultproperties\"",
    "\"super\"",
    "\"switch\"",
    "\"transient\"",
    "\"travel\"",
    "\"true\"",
    "\"unreliable\"",
    "\"until\"",
    "\"var\"",
    "\"virtual\"",
    "\"void\"",
    "\"within\"",
    "\"while\"",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<DECIMAL_FLOATING_POINT_LITERAL>",
    "<DECIMAL_EXPONENT>",
    "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
    "<HEXADECIMAL_EXPONENT>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"=\"",
    "\"@\"",
    "\"$\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"**\"",
    "\"@=\"",
    "\"$=\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\">>>\"",
    "\">>\"",
    "\">\"",
    "<ALL>",
  };

}
